### ISSUE TITLE
Remove 'raise hand'?

### ISSUE THREAD

**Issue by 0atman** [alphagov/hand-signals#32]
Imitation is the sincerest form of flattery: Google integrated a raise hand feature a while back, and now it's got a few more features (lowering when you speak, notification sound so full-screen presenters can hear it etc).

I think the duplication could be usefully removed.

**Comment by whi-tw** [comment]
(or, could this feature be triggered by this plugin - to keep everything in the same place?)

**Comment by 0atman** [comment]
@whi-tw sounds like it could make the code more brittle to changes? The PR has been merged anyway :laughing:
