### ISSUE TITLE
Make some of the signals hang around for a bit longer

### ISSUE THREAD

**Issue by whi-tw** [alphagov/hand-signals#6]
"Raise Hand" is useful, as it hangs around until dismissed - maybe some of the other signals should do the same (want to respond / point of order etc?)

**Comment by pauldougan** [comment]
you beat me to it

**Comment by LeePorte** [comment]
Yes I think this seems like a good idea. I'll start with direct response and point of order

**Comment by LeePorte** [comment]
Let me know if this meets your needs once you've tried 0.0.6

**Comment by whi-tw** [comment]
Looks solved to me! thank you!
