### ISSUE TITLE
Clicking the tooltip of a signal triggers that signal

### ISSUE THREAD

**Issue by whi-tw** [alphagov/hand-signals#7]
Common set of actions:

1. hover over the "more" arrow
2. move mouse over "I want to respond"
3. move mouse to "I agree"
4. accidentally click on "I want to respond"
5. send the wrong signal
6. repeat

**Comment by whi-tw** [comment]
Unsure if this is a feature?

Not sure what the solution would be.. perhaps not keep the tooltip around when hovering over it?

**Comment by LeePorte** [comment]
Hopefully this should be fixed for you in 0.0.7. chrome web store is being slow to approve the previous verson. as soon as that;s clear I'll get the new version uploaded.

**Comment by whi-tw** [comment]
Looks solved to me! thank you!
