### ISSUE TITLE
add commonly used signs to the interface

### ISSUE THREAD

**Issue by pauldougan** [alphagov/hand-signals#8]
![image](https://user-images.githubusercontent.com/34273121/81925633-ae6bdb00-95d8-11ea-91ab-00bbc857a0f5.png)

at the moment the only sign nailed to the interface is "i want to speak", can we also have "agree" and "disagree"

**Comment by LeePorte** [comment]
Which signals would you consider common?

**Comment by LeePorte** [comment]
Let me know if this meets your needs once you've tried 0.0.6

**Comment by pauldougan** [comment]
great looks good 
![image](https://user-images.githubusercontent.com/34273121/82062308-d2efb200-96c1-11ea-939b-a9f16eb93125.png)
